include global

A_CONFIG_APP_BIN := $(A_CONFIG_APP_TITLE).html

A_CONFIG_SCREEN_WIDTH := 96
A_CONFIG_SCREEN_HEIGHT := 64

Z_ROOT := ..
Z_DIR_GFX := assets/gfx
Z_DIR_SFX := assets/sfx

A_CONFIG_EMBED_PATHS_EMSCRIPTEN := \
	$(addprefix $(Z_DIR_GFX)/, $(notdir $(wildcard $(Z_ROOT)/$(Z_DIR_GFX)/*.png))) \
	$(addprefix $(Z_DIR_SFX)/, $(notdir $(wildcard $(Z_ROOT)/$(Z_DIR_SFX)/*.wav))) \

include $(A2X_PATH)/make/emscripten
