A_CONFIG_APP_NAME := neonrattle.html
A_CONFIG_DIR_SRC := neonrattle

Z_ROOT := ..
Z_DIR_GFX := assets/gfx
Z_DIR_SFX := assets/sfx

A_CONFIG_EMBED_PATHS_EMSCRIPTEN := \
	$(addprefix $(Z_DIR_GFX)/, $(notdir $(wildcard $(Z_ROOT)/$(Z_DIR_GFX)/*.png))) \
	$(addprefix $(Z_DIR_SFX)/, $(notdir $(wildcard $(Z_ROOT)/$(Z_DIR_SFX)/*.wav))) \

include $(A2X_PATH)/make/project/Makefile.emscripten
